### ISSUE TITLE
Minor problem with packages

### ISSUE THREAD

**Issue by fperana** [delphi-blocks/WiRL#22]
In one of the latest commits the unit Neon.Core.Serializers was divided in three separate units: Neon.Core.Serializers.DB, Neon.Core.Serializers.RTL, Neon.Core.Serializers.VCL, but the package was not updated to reflect this change, so now it doesn't compile.

**Comment by paolo-rossi** [comment]
Hi Franco,

I can't see the issue in the actual code, can you confirm it's still present?

Paolo.

**Comment by fperana** [comment]
Hi Paolo,

I've just cloned your repo and the prolem is still there:

Package NeonRunTime.dpk references "Neon.Core.Serializers in '..\..\Source\Neon.Core.Serializers.pas'," that doesn't exists anymore. This is in all three packages (delphi 10.1, 10.2 and 10.3).

Can you confirm?

**Comment by hbxfwjww** [comment]
I also have the same problem. After modifying Neon.Core.Serializers to Neon.Core.Serializers.RTL, it can be compiled and installed.
