### ISSUE TITLE
Problema richiesta HTTP-POST da applicativo Android

### ISSUE THREAD

**Issue by aRicciardiNeobit** [delphi-blocks/WiRL#30]
Buongiorno,
sto riscontrando problemi ad eseguire una richiesta HTTP-POST da un'applicativo Android (sviluppato tramite Flutter 2.2.2, Dart 212.45) verso il server REST WiRL.
In particolare quando provo ad eseguire il login, tramite '_TWiRLAuthBasicResource_', il servizio non riceve nessun valore che ho impostato nell'Header della chiamata POST:

    [POST, Produces(TMediaType.APPLICATION_JSON)]
    function DoLogin([HeaderParam('Authorization')] const AAuth: string): TWiRLLoginResponse;
--> **AAuth** = ''

Provando ad eseguire la stessa chiamata da Postman, usando come valore della chiave 'Authorization': 
       'Basic ' + base64Encode(utf8.encode('username:password')); 
il servizio riceve il valore corretto 
       --> **AAuth** = 'Basic cGFvbG86bXlwYXNzd29yZA=='
e mi restituisce il Token generato 

Ho provato ad utilizzare il server presente nella **Demo 03.Authorization**, ma anche in questo caso, le chiamate tramite Postman vengono eseguite, ancora niente per quelle lanciate dall'applicativo Android.

Si presenta la stessa situazione anche per le tipologie di autenticazione '_TWiRLAuthFormResource_', '_TWiRLAuthBodyResource_'

Ho configurato il server nel seguente modo:

    FServer.AddEngine<TWiRLEngine>('/rest')
       .SetEngineName('RESTEngine')
       .AddApplication('/loginService')
       .SetResources('*')
       .SetFilters('*')
    
    .Plugin.Configure<IWiRLConfigurationAuth>
        .SetTokenType(TAuthTokenType.JWT)
        .SetTokenLocation(TAuthTokenLocation.Bearer)
        .BackToApp
    
    .Plugin.Configure<IWiRLConfigurationCORS>
        .SetOrigin('*')
        .SetMethods('HEAD, GET, PUT, POST, DELETE, OPTIONS')
        .SetHeaders('*')
        .BackToApp;

Ho aggiunto la configurazione CORS (rispetto all'esempio 03.Authorization)  perché precedentemente, usando servizi sviluppati in MARS, avevo risolto il problema aggiungendo nel file di configurazione .ini del server:
[DefaultEngine]
CORS.Enabled=true

Grazie mille.

**Comment by lminuti** [comment]
Ciao, tieni conto che la configurazione **SetHeaders** su **IWiRLConfigurationCORS** non fa nient'altro che valorizzare l'header **Access-Control-Allow-Headers**. Se vai a vedere la documentazione però il valore "*" non comprende l'header **Authorization**. Devi proprio specificarlo.

> The value "\*" only counts as a special wildcard value for requests without credentials (requests without HTTP cookies or HTTP authentication information). In requests with credentials, it is treated as the literal header name "\*" without special semantics. **Note that the Authorization header can't be wildcarded and always needs to be listed explicitly**.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Headers
