### ISSUE TITLE
Client MultiPart 

### ISSUE THREAD

**Issue by Giottino69** [delphi-blocks/WiRL#37]
Nella demo HelloWord c'è l'esempio di un POST MultiPart  (PostMultiPartExample), sul client però non c'è, come si implementa lato client?
Grazie.

**Comment by lminuti** [comment]
Scusa per il ritardo nella risposta. Al momento il client non supporta i messaggi MultiPart ma sicuramente è una cosa che aggiungeremo nelle prossime release.

**Comment by bioman-jeun** [comment]
POST MultiPart Client Example?

**Comment by paolo-rossi** [comment]
[Added "multipart/form-data" support to TWiRLClient](https://github.com/delphi-blocks/WiRL/commit/21599301e5e879bbe47b334d030c5c4f6253593d)
