### ISSUE TITLE
Several sources have inconsistent line endings

### ISSUE THREAD

**Issue by davideangeli** [delphi-blocks/WiRL#54]
I'm recompiling the latest version I just downloaded and since I got some strange errors during compilation (Delphi 12.1) I noticed that there are several sources that only have the LF and not the CRLF at the end of each line. I fixed the sources with Project Magician and now I no longer have compilation problems. Is this a problem with my source clone from GitHub or does the problem lie at the source?

**Comment by paolo-rossi** [comment]
Hello Davide,

do you have a list of such files? so I can easily convert them.. 

Thanks Paolo.

**Comment by davideangeli** [comment]
Hello Paolo,

I only checked the ".pas" files and from the list below I can say that the majority have the CRLF inconsistency and I hope I haven't forgotten any files... Maybe you'd better reopen them all for safety with a tool that fix CRLFs (like Uwe Raabe's Project Magician). I've just pulled the latest available version (yesterday) and these are the pas files with the problem:

- WiRL.Client.Application.Editor.pas
- WiRL.Client.Filters.pas
- WiRL.Client.Register.pas
- WiRL.Client.ResourceDebugger.pas
- WiRL.Client.ResourceDebuggerHeader.pas
- WiRL.Client.ResourceHeaderEditor.pas
- WiRL.http.Client.Editor.pas
- WiRL.http.Client.Indy.pas
- WiRL.http.Client.Interfaces.pas
- WiRL.http.Client.NetHttp.pas
- WiRL.Configuration.Auth.pas
- WiRL.Configuration.Compression.pas
- WiRL.Configuration.Converter.pas
- WiRL.Configuration.Core.pas
- WiRL.Configuration.CORS.pas
- WiRL.Configuration.JWT.pas
- WiRL.Configuration.Neon.pas
- WiRL.Configuration.OpenAPI.pas
- WiRL.Core.Application.Editor.pas
- WiRL.Core.Application.Worke.pas
- WiRL.Core.Context.pas
- WiRL.Core.Context.Server.pas
- WiRL.Core.Converter.pas
- WiRL.Core.GarbageCollector.pas
- WiRL.Core.Injection.pas
- WiRL.Core.MessageBody.Classes.pas
- WiRL.Core.MessageBody.Default.pas
- WiRL.Core.Metadata.pas
- WiRL.Core.Metadata.XMLDoc.pas
- WiRL.Core.OpenAPI.pas
- WiRL.Core.OpenAPI.Resource.pas
- WiRL.Core.Register.pas
- WiRL.Core.Tuples.pas
- WiRL.Core.Validators.pas
- WiRL.Engine.Core.pas
- WiRL.Engine.FileSystem.pas
- WiRL.Engine.HTTP.pas
- WiRL.Engine.REST.pas
- WiRL.Engine.WebServer.pas
- WiRL.http.Accept.Charset.pas
- WiRL.http.Accept.Encoding.pas
- WiRL.http.Accept.Language.pas
- WiRL.http.Accept.Parser.pas
- WiRL.http.Cookie.pas
- WiRL.http.Filters.pas
- WiRL.http.Filters.Compression.pas
- WiRL.http.Filters.CORS.pas
- WiRL.http.Headers.pas
- WiRL.http.MultipartData.pas
- WiRL.http.Server.pas
- WiRL.http.Server.Editor.pas
- WiRL.http.Server.Interfaces.pas
- WiRL.Data.MessageBody.Default.pas
- WiRL.Data.FireDAC.MessageBody.Default.pas
- WiRL.Data.FireDAC.Persistence.pas
- WiRL.Data.FireDAC.Updates.pas
- WiRL.Console.Base.pas
- WiRL.Console.Daemon.pas
- WiRL.Console.Factory.pas
- WiRL.Console.Posix.Daemon.pas
- WiRL.Console.Posix.Syslog.pas
- WiRL.Console.Standard.pas
- WiRL.Console.Types.pas
- WiRL.Data.Resolver.pas
- WiRL.Engine.Proxy.pas
- WiRL.GraphQL.Base.pas
- WiRL.MessageBody.DJSON.pas
- WiRL.MessageBody.OXML.pas
- WiRL.MessageBody.SingleRecord.pas
- WiRL.MessageBody.SuperObject.pas
- WiRL.Wizards.Dialogs.ServerProject.pas
- WiRL.Wizards.Modules.Classes.pas

**Comment by paolo-rossi** [comment]
Davide,

I checked with several tools and I can't find CR or LF alone in these files, there are only CRLF, perhaps some git configuration on your part?

Paolo.

**Comment by davideangeli** [comment]
Paolo, 

Maybe... but still I can't understand why there are some files with the correct CRLF and others not... I'm investigating on git. I use SmartGit to pull sources from GitHub but only with WiRL am I experiencing this anomaly.

Davide

**Comment by davideangeli** [comment]
Paolo,

I think that could be something on github. I've just downloaded the zip file from it and the files inside have the problem. This is one of them opened with the Total Commander hexadecimal viewer:

![image](https://github.com/user-attachments/assets/c2325f25-0dc9-4f7a-a55d-426eb3a8ce65)

Davide

**Comment by paolo-rossi** [comment]
Davide,

yes, I don't know why but the zip download from GitHub has all the files with LF (Unix style) but I checked other repositories and it's all the same as WiRL.. so, yes probably has something to do with GitHub.

I'm going to close this with this comment given the sources itself are not affected but I'll investigate further if there is some GitHub configuration for the zip download..

Paolo.

**Comment by davideangeli** [comment]
Paolo, 

in the zip file not all the files have the problem, I've the exact situation that I've pulling the sources with smartgit... For instance the file "WiRL.Client.Application.pas" is correct in the zip file as it is correct in my local repository. It would seem that the files stored on github bring the problem with them. I don't know if I can explain myself well!
