### ISSUE TITLE
Sending a request with DELETE and Json in the body.

### ISSUE THREAD

**Issue by Rea-Soft** [delphi-blocks/WiRL#62]
I can't send a "DELETE" request with json in the body with WIRL. Is there a way?

**Comment by lminuti** [comment]
Are you sure? I wrote the following code and it works (I tested the code with [Bruno](https://www.usebruno.com/))

```pascal
  [Path('/helloworld')]
  THelloWorldResource = class
  public
    [DELETE]
    [Path('/body')]
    [Consumes(TMediaType.APPLICATION_JSON)]
    [Produces(TMediaType.APPLICATION_JSON)]
    function PostData([BodyParam] const ABody: string): string;
  end;

///////////////

function THelloWorldResource.PostData(const ABody: string): string;
begin
  Result := ABody;
end;


```

**Comment by Rea-Soft** [comment]
Thanks for the quick response and sorry if I was unclear. I am implementing a rest client with WIRL. My problem is the client call on a Rest server implemented with another programming language. I am asked to delete a data with the DELETE method whose identification occurs via data passed as json in the body of the request. 
The specification is of the type: **[DELETE]** .../rest/vk1/cancella
_request body_
{"id":99,
"reason":"wrong value"
}.
I did not find the right method in WIRL, is there one?
Thank you very much
